// TikZ serialiser, for a documented subset.
//
// TikZ output is the PROJECTED 2D figure, not the scene. It does not round-trip back into
// Byrne, and it is not meant to: it is a derived format for dropping a figure into a
// paper whose other figures are TikZ. What is and is not exported is stated in the file's
// own header, so the reader of the .tex finds out from the file rather than from a
// changelog.

import { Figure, Prim, Pt } from './ir.js'
import { plain } from './labels.js'

const n = (x: number): string => String(Math.round(x * 1000) / 1000)

/** Points to TikZ centimetres, with y flipped back to a mathematical axis. */
const P = (p: Pt, h: number): string => `(${n(p[0] / 28.3465)},${n((h - p[1]) / 28.3465)})`

export interface TikzOptions {
  /** Named parameters to emit as \pgfmathsetmacro so the reader can vary the figure. */
  readonly parameters?: ReadonlyArray<{ name: string; value: string }>
  readonly standalone?: boolean
}

const NOT_EXPORTED = [
  'gradient fills',
  'clipping paths other than the page rectangle',
  'the viewport surface shading',
  'any 3D information: this is the projected figure, not the scene',
  'round-tripping back into Byrne',
]

export function toTikz(fig: Figure, opts: TikzOptions = {}): string {
  const out: string[] = []
  out.push(`% Generated by Byrne from a live model. Regenerate; do not hand-edit.`)
  out.push(`%`)
  out.push(`% NOT exported to TikZ:`)
  for (const item of NOT_EXPORTED) out.push(`%   - ${item}`)
  if (fig.caveats.length) {
    out.push(`%`)
    out.push(`% Approximations in this figure:`)
    for (const c of fig.caveats) out.push(`%   - ${c}`)
  }
  out.push('')

  if (opts.standalone) {
    out.push('\\documentclass[tikz,border=2pt]{standalone}', '\\usetikzpicture', '\\begin{document}')
  }

  out.push('\\tikzset{')
  out.push('  byrne force/.style={draw=byrneforce, line width=0.4pt, -{Stealth[length=2mm]}},')
  out.push('  byrne structure/.style={draw=byrnestructure, line width=0.4pt},')
  out.push('  byrne guide/.style={draw=byrneguide, line width=0.3pt, dashed},')
  out.push('}')
  out.push('\\definecolor{byrneforce}{HTML}{C0392B}')
  out.push('\\definecolor{byrnestructure}{HTML}{2B2B28}')
  out.push('\\definecolor{byrneguide}{HTML}{9A9A93}')
  out.push('\\definecolor{byrnefield}{HTML}{8E44AD}')
  out.push('')

  for (const p of opts.parameters ?? []) {
    out.push(`\\pgfmathsetmacro{\\${p.name.replace(/[^A-Za-z]/g, '')}}{${p.value}}`)
  }
  if (opts.parameters?.length) out.push('')

  out.push('\\begin{tikzpicture}')
  for (const p of fig.prims) out.push('  ' + prim(p, fig.height))
  out.push('\\end{tikzpicture}')
  if (opts.standalone) out.push('\\end{document}')
  return out.join('\n') + '\n'
}

function opt(p: Prim): string {
  const s = p.style
  const bits = [`draw={rgb,255:red,${hex(s.stroke, 0)};green,${hex(s.stroke, 1)};blue,${hex(s.stroke, 2)}}`]
  bits.push(`line width=${n((s.weight ?? 1) * 0.4)}pt`)
  if (s.arrowHead) bits.push('-{Stealth[length=2mm]}')
  if (s.fill && s.fill !== 'none') bits.push('fill opacity=0.06, fill=black')
  if (s.dash?.length) bits.push('dashed')
  return `[${bits.join(', ')}]`
}

function hex(color: string | undefined, channel: number): number {
  const c = color ?? '#1b1b1a'
  const m = /^#([0-9a-f]{6})$/i.exec(c)
  if (!m) return 0
  return parseInt(m[1]!.slice(channel * 2, channel * 2 + 2), 16)
}

function prim(p: Prim, h: number): string {
  switch (p.kind) {
    case 'line':
      return `\\draw${opt(p)} ${P(p.a, h)} -- ${P(p.b, h)};`
    case 'polyline':
      return `\\draw${opt(p)} ${p.pts.map((q) => P(q, h)).join(' -- ')}${p.closed ? ' -- cycle' : ''};`
    case 'circle':
      return `\\draw${opt(p)} ${P(p.c, h)} circle [radius=${n(p.r / 28.3465)}];`
    case 'ellipse':
      return `\\draw${opt(p)} ${P(p.c, h)} ellipse [x radius=${n(p.rx / 28.3465)}, y radius=${n(p.ry / 28.3465)}, rotate=${n((p.rot * 180) / Math.PI)}];`
    case 'arc': {
      const a0 = (p.a0 * 180) / Math.PI
      const a1 = (p.a1 * 180) / Math.PI
      const start: Pt = [p.c[0] + p.r * Math.cos(p.a0), p.c[1] - p.r * Math.sin(p.a0)]
      return `\\draw${opt(p)} ${P(start, h)} arc [start angle=${n(a0)}, end angle=${n(a1)}, radius=${n(p.r / 28.3465)}];`
    }
    case 'cubic':
      return `\\draw${opt(p)} ${p.pts.map((q) => P(q, h)).join(' .. controls .. ')};`
    case 'label':
      // The LaTeX goes through verbatim: this is the one format where a label is already
      // in its final language.
      return `\\node[anchor=${anchor(p.anchorX, p.anchorY)}] at ${P(p.at, h)} {$${p.latex}$};`
  }
}

function anchor(x: number, y: number): string {
  const v = y > 0.2 ? 'south' : y < -0.2 ? 'north' : ''
  const hz = x > 0.2 ? 'west' : x < -0.2 ? 'east' : ''
  return `${v}${v && hz ? ' ' : ''}${hz}` || 'center'
}

export { plain }
